#!/usr/bin/python3
# encoding: utf-8
# PYTHON_ARGCOMPLETE_OK

from L4.upper.stack_factory import StackFactory
from L5.upper.opmode_factory import OpModeFactory

###

def main():
    stack = StackFactory().create()
    mode = OpModeFactory(stack).create()
    mode.run()

if 'main' in __name__:
    import sys
    sys.exit(main())
